### ISSUE TITLE
Fix eq reference in "kernel trick"

### ISSUE THREAD

**Issue by SvenNekula** [JoshuaSimon/Kernel-Learning#3]
Not sure if I just didn't get it, but labelling the equations was a huge pain in the ass.
Adding to that, it seems like you can only reference equations in the same markdown chunk, however it's not possible to combine the chunks containing the two equations.  So that has to be fixed I guess.

**Comment by JoshuaSimon** [comment]
For a workaround the notebook extension "jupyter_contrib_nbextensions" can be used. See https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/index.html 

From this bundle the "MathJax Equation Numbering" extension can be used to enable auto numbering (no longer `\tag{}` needs to be used) and cross references over several markdown cells with `\eqref{}`.


This extension is installed via a python package and has to be configured for the local notebook client. An installation guide can be found here: https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/install.html

If we decide to go with this workaround, the jupyter notebook in the docker container has to be configured this way too. So we should check this approach in the docker container first, before committing to the master branch. Also this only seems to work within jupyter itself. The VS Code notebook is still broken and can't handle the extension.

**Comment by JoshuaSimon** [comment]
A working example can be found in a new branch https://github.com/JoshuaSimon/Kernel-Learning/blob/Fix--Equation-numbering-and-cross-reference/src/kernel_learning.html 

A pull request has not been created yet.

**Comment by JoshuaSimon** [comment]
Finally found a native markdown solution which should at least work in GitHub flavoured markdown. References can be made by using in HTML `<a>` tag like for example `<a id="Bronstein">[Bronstein, 2020]</a>` at the position you want to jump to. To reference this position in any other place in the markdown file one can use `[link name](#a-tag-id)`. With this example a citation would look like this: `[[Bronstein, 2020]](#Bronstein)`.

An analog approach can be considered for equations. Place an `<a>` tag like `<a id="eq_test"></a>` before the equation. Since the `<a>` tag does not contain any text, no text is displayed in the markdown render. Referencing this equation works like `[Test](#eq_11)`. The markdown render would then display Test as clickable link.
